mainpage/urls.py
from django.urls import path
from django.views.generic.base import RedirectView

from mainpage import views

app_name = 'mainpage'

urlpatterns = [
    path('', RedirectView.as_view(url='tasks/')),
    path('tasks/', views.Home.as_view(), name='home'),
    path('settings/', views.Settings.as_view(), name='settings'),
    path('about/', views.About.as_view(), name='about'),
    path('statuses/<int:pk>/delete/', views.DeleteStatus.as_view(),
         name='delete_status'),
    path('statuses/new/', views.CreateStatus.as_view(), name='create_status'),
    path('statuses/<int:pk>/edit/', views.UpdateStatus.as_view(),
         name='edit_status'),
    path('tasks/<int:pk>/', views.TaskView.as_view(), name='view_task'),
    path('tasks/new', views.CreateTask.as_view(), name='new_task'),
    path('tasks/<int:pk>/edit/', views.EditTask.as_view(), name='edit_task'),
    path('tasks/<int:pk>/delete/', views.DeleteTask.as_view(),
         name='delete_task'),
    path('signup/', views.SignUp.as_view(), name='signup'),
]

task_manager/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('mainpage.urls', namespace='mainpage')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mainpage/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class Status(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name


class Task(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True)
    status = models.ForeignKey(Status,
                               default=1,
                               on_delete=models.CASCADE,
                               related_name='statuses')
    creator = models.ForeignKey(User,
                                on_delete=models.CASCADE,
                                related_name='creators')
    assigned_to = models.ForeignKey(User,
                                    on_delete=models.CASCADE,
                                    related_name='doers')
    tags = models.ManyToManyField(Tag,
                                  default=1,
                                  related_name='tags')

    def get_absolute_url(self):
        return reverse('mainpage:view_task', kwargs={"pk": self.pk})

    def __str__(self):
        return self.name

    def random_taskname():
        import random
        ROUTINE_TASKS = [
            'Go for a walk', 'Clean up something', 'Read 30 min',
            'Solve kata', 'Do small workout', 'Pat cat',
            'Straight your back', 'Make a stretch', 'Make coffee'
        ]
        return random.choice(ROUTINE_TASKS)

mainpage/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from mainpage.models import Status, Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['name',
                  'description',
                  'status',
                  'creator',
                  'assigned_to',
                  'tags']
        labels = {
            'name': 'Task name',
            'description': 'Task details',
            'status': 'Status',
            'creator': 'Creator',
            'assigned_to': 'Assigned',
        }


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2', ]


class StatusForm(forms.ModelForm):
    class Meta:
        model = Status
        fields = ['name', ]
        labels = {
            'name': 'Status',
        }

mainpage/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import (CreateView, DeleteView, DetailView, FormView,
                                  ListView, UpdateView)
from django.views.generic.base import TemplateView

from mainpage.forms import SignUpForm, StatusForm, TaskForm
from mainpage.models import Status, Tag, Task


class Home(LoginRequiredMixin, ListView):
    login_url = '/accounts/login/'
    template_name = 'home.html'
    model = Task
    context_object_name = 'tasks'

    @staticmethod
    def add_filter(filters, lookup, query, if_not=None):
        if query and query != if_not:
            filters[lookup] = query

    def get_queryset(self):
        qs = super().get_queryset()
        tag = self.request.GET.get('tag')
        status = self.request.GET.get('status')
        assigned_to = self.request.GET.get('assigned_to')
        filters = {}
        self.add_filter(filters, 'status__name', status, if_not='All statuses')
        self.add_filter(filters, 'tags__name', tag, if_not='All tags')
        self.add_filter(filters, 'assigned_to__username', assigned_to,
                        if_not='Assigned to all')
        if 'mytasks' in self.request.GET:
            self.add_filter(filters, 'assigned_to__username',
                            self.request.user)
        if 'reset' in self.request.GET:
            filters = {}
        qs = qs.filter(**filters)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'queryset': self.get_queryset(),
            'statuses': Status.objects.all(),
            'tags': Tag.objects.all(),
            'users': User.objects.all(),
            })
        return context


class Settings(LoginRequiredMixin, ListView):
    login_url = '/accounts/login/'
    template_name = 'pages/settings.html'
    model = Status
    context_object_name = 'statuses'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'form': StatusForm(),
            'statuses': Status.objects.all(),
            })
        return context


class About(TemplateView):
    template_name = "pages/about.html"


class CreateStatus(CreateView):
    template_name = 'pages/settings.html'
    model = Status
    success_url = reverse_lazy('mainpage:settings')
    form_class = StatusForm


class DeleteStatus(DeleteView):
    template_name = 'pages/settings.html'
    model = Status
    success_url = reverse_lazy('mainpage:settings')


class UpdateStatus(UpdateView):
    template_name = 'pages/status_edit.html'
    model = Status
    success_url = reverse_lazy('mainpage:settings')
    fields = ['name']


class TaskView(DetailView):
    template_name = 'tasks/view_task.html'
    model = Task


class CreateTask(CreateView):
    template_name = 'tasks/new_task.html'
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy('mainpage:home')

    def get_initial(self):
        initial = super(CreateTask, self).get_initial()
        initial['name'] = Task.random_taskname()
        initial['creator'] = self.request.user
        initial['assigned_to'] = self.request.user
        initial['description'] = 'Things to do:'
        return initial


class EditTask(UpdateView):
    template_name = 'tasks/edit_task.html'
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy('mainpage:home')


class DeleteTask(DeleteView):
    template_name = 'tasks/task_confirm_delete.html'
    model = Task
    success_url = reverse_lazy('mainpage:home')


class SignUp(FormView):
    form_class = SignUpForm
    success_url = reverse_lazy('mainpage:home')
    template_name = 'registration/signup.html'

    def form_valid(self, form):
        form.save()
        username = self.request.POST['username']
        password = self.request.POST['password1']
        user = authenticate(username=username, password=password)
        login(self.request, user)
        return redirect(self.success_url)

templates/base.html
{% load bootstrap4 %}
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS and JavaScript -->
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

    <link href="{% static 'cover.css' %}" rel="stylesheet">
    <link rel="icon" href="{% static 'favicon.ico' %}">
    <title>{% block title %}{% endblock %}</title>

  </head>


  <body>
    <div class="cover-container text-center d-flex w-100 p-3 mx-auto flex-column">
      {% include 'components/header.html' %}
      {% block content %} {% endblock %}
      {% include 'components/footer.html' %}
    </div>
  </body>
</html>

templates/components/footer.html
{% load static %}
<footer class="mastfoot mt-auto">
  <div class="inner">
    <p>Slavarobotam <a href="https://github.com/slavarobotam/python-project-lvl4">@github</a></p>
  </div>
</footer>

templates/components/header.html
{% load static %}
<header class="masthead mb-auto">
  <div class="inner">
    <h3 class="masthead-brand"><a href="{% url 'mainpage:home' %}">Task manager</a></h3>
    <nav class="nav nav-masthead justify-content-center">
        <a
          {% if '/' == request.path or '/tasks/' == request.path %}
            class="nav-link active"
          {% else %}
            class="nav-link"
          {% endif %}
          href="{% url 'mainpage:home' %}">Home</a>

        <a
          {% if 'settings' in request.path %}
            class="nav-link active"
          {% else %}
            class="nav-link"
          {% endif %}
          href="{% url 'mainpage:settings' %}">Settings</a>

        <a
          {% if 'about' in request.path %}
            class="nav-link active"
          {% else %}
            class="nav-link"
          {% endif %}
          href="{% url 'mainpage:about' %}">About</a>
    </nav>
  </div>
</header>

templates/contact.html
{% extends "base.html" %}

{% block title %}Main{% endblock %}

{% block content %}
<main role="main" class="inner cover">
    <h1 class="cover-heading">Say hello</h1>
    <p class="lead"><a href="mailto:zefiratakuet@yandex.ru">click here to mail me</a></p>
</main>
{% endblock %}

templates/header.html
{% load static %}
<header class="masthead mb-auto">
  <div class="inner">
    <h3 class="masthead-brand">Task manager &lt;3</h3>
    <nav class="nav nav-masthead justify-content-center">
        <a
          {% if '/' == request.path %}
            class="nav-link active"
          {% else %}
            class="nav-link"
          {% endif %}
          href="{% url 'mainpage:task_list' %}">Home</a>

        <a
          {% if 'features' in request.path %}
            class="nav-link active"
          {% else %}
            class="nav-link"
          {% endif %}
          href="{% url 'mainpage:features' %}">Features</a>

        <a
          {% if 'contact' in request.path %}
            class="nav-link active"
          {% else %}
            class="nav-link"
          {% endif %}
          href="{% url 'mainpage:contact' %}">Contact</a>
    </nav>
  </div>
</header>

templates/home.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block title %} Tasks {% endblock %} 
{% block content %}

<main role="main" class="inner cover">

    <!-- Filters -->
    <form method="GET" class="mt-3" action=".">{% csrf_token %}
        {% if form.errors %} {{ form.errors }} {% endif %}
        <!-- Filter row -->
        <div class="form-inline justify-content-center mt-4">
            <select id="assigned_to" class="form-control col-2 mr-2" name="assigned_to">
                <option class="text-align-center" selected>Assigned to all</option>
                {% for user in users %}
                <option value="{{ user }}">{{ user }}</option>
                {% endfor %}
            </select>
            <select id="status" class="form-control col-2 mr-2" name="status">
                <option selected>All statuses</option>
                {% for status in statuses %}
                <option value="{{ status }}">{{ status }}</option>
                {% endfor %}
            </select>
            <select id="tag" class="form-control col-2 mr-2" name="tag">
                <option selected>All tags</option>
                {% for tag in tags %}
                <option value="{{ tag }}">{{ tag }}</option>
                {% endfor %}
            </select>
                <button name='apply' class="btn btn-info mr-2" type="submit" >Apply</button>
                <button name='reset' class="btn btn-secondary mr-2" type='submit'>Reset</button>
        </div>
    </form>

    <!-- Head of task container -->
    <div class="row my-3 border-bottom border-secondary text-left">
        <div class="col-1 ">Tags</div>
        <div class="col-3 ">Name</div>
        <div class="col-5 ">Description</div>
        <div class="col-1 ">Status</div>
        <div class="col-1 ">Creator</div>
        <div class="col-1">Assigned</div>
    </div>

    <!-- Tasks -->
    {% for task in queryset %}
        <div class="row row-hover mb-2 text-left position-relative">
                <div class="col-1 ">{{ task.tags.all|join:", "|truncatewords:3 }}</div>
                <div class="col-3 position-static"><a class="stretched-link text-decoration-none" href="{{ task.get_absolute_url }}">
                    {{ task.name|truncatewords:10  }}</a></div>
                <div class="col-5 ">{{ task.description|linebreaks|truncatewords:15 }}</div>
                <div class="col-1 text-truncate">{{ task.status }}</div>
                <div class="col-1 text-truncate ">{{ task.creator }}</div>
                <div class="col-1  text-truncate">{{ task.assigned_to }}</div>
        </div>
    {% endfor %}

    <!-- Buttons "My tasks" and "Add new" -->
    <form method="GET" class="mt-3" action=".">{% csrf_token %}
        <div class="row justify-content-center mt-4">
            <button name='mytasks' class="btn btn-primary mr-2" type='submit'>My tasks</button>
            <a href="{% url 'mainpage:new_task' %}" class="btn btn-success mr-2" role="button">Add new</a>
           
        </div>
    </form>
</main>
{% endblock %}

templates/pages/about.html
{% extends "base.html" %}

{% block title %}Main{% endblock %}

{% block content %}
<main role="main" class="inner cover ">
    <h1>Task manager</h1>
        <p class="text-left mt-4">Task_manager is a small web application helping to deal with tasks.
            Designed for usage for a small team but also suitable for single person usage.</p>
    <h3 id="features">Features</h3>
    <ul class="text-left">
        <li>Tasks with simple but enough detailization: consist of fields <code>Name</code>, <code>Description</code>, <code>Assigned_to</code>, <code>Creator</code>, <code>Tags</code> and <code>Status</code>.
            <ul>
                <li>Default setting for <code>Assigned_to</code> and <code>Creator</code> — current user name.</li>
                <li>Default task status is &quot;New&quot;.</li>
                <li>Available multiple choice for tags.</li>
            </ul>
        </li>
        <li>Equal maximum rights for all users: read, edit and delete tasks and same for statuses.</li>
        <li>Filters for fields <code>Assigned_to</code>, <code>Tags</code>, <code>Statuses</code></li>
        <li>Button &quot;My tasks&quot; for quick showing current user&#39;s tasks.</li>
        <li>Calm dark theme</li>
    </ul>

    <h3 class="cover-heading">Contacts</h1>
    <p class="lead">You can <a href="mailto:zefiratakuet@yandex.ru"><u>write me</u></a> your feedback</p>
    <a href="{% url 'mainpage:home' %}" class="btn btn-secondary mx-2" role="button">Back</a>
</main>
{% endblock %}

templates/pages/contact.html
{% extends "base.html" %}

{% block title %}Main{% endblock %}

{% block content %}
<main role="main" class="inner cover">
    <h1 class="cover-heading">Say hello</h1>
    <p class="lead">via <a href="mailto:zefiratakuet@yandex.ru"><u>mail</u></a></p>
</main>
{% endblock %}

templates/pages/settings.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block title %}Settings{% endblock %}
{% block content %}
<h1>Settings</h1>

    <!-- Showing list of statuses -->
    {% if statuses %}
        <h3 class="my-2">Edit, delete and create new statuses</h3>
        {% for status in statuses %}
        <div class="row justify-content-center my-2">
            <div class="col-1 text-center  mr-2 p-0">{{ status.name }}</div>

            <form  action="{% url 'mainpage:edit_status' status.id %}" class="col-1 p-0" method="get" >{% csrf_token %}
                <button  type="submit" class="btn btn-sm btn-outline-primary mr-2">Edit</button>
            </form>
            <form action="{% url 'mainpage:delete_status' status.id %}" class="col-1 p-0" method="post" >{% csrf_token %}
                <button  type="submit" class="btn btn-sm btn-outline-danger">Delete</button>
            </form>
        </div>
        {% endfor %}
    {% endif %}

    <!-- Create new status -->
    <form action="{% url 'mainpage:create_status' %}" class="form-inline justify-content-center mt-4" method="post" >{% csrf_token %}
        <div class="form-group row">
            <label for="newstatus" class="col-2 text-nowrap">Add new:</label>
            {% bootstrap_field form.name layout="horizontal" size="small" horizontal_field_class='col-md-8 mx-3' show_label=False %}
            <button type="submit" class="btn btn-success">Create</button>
            <a href="{% url 'mainpage:home' %}" class="btn btn-secondary mx-2" role="button">Back</a>
        </div>
    </form>

    <!-- Logout -->
    <div class="row justify-content-center mt-3 p-1">
        <p class="text-muted mt-5">If you are not {{ request.user }}, you can <u><a class="text-muted" href="{% url 'logout' %}">logout</a></u></p>
        
    </div>

{% endblock %}

templates/pages/status_edit.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block title %}Edit{% endblock %}

{% block content %}
<div class="container justify-content-center">
    <h3>Edit status</h3>
    <form class="form-inline justify-content-center mt-5" method="post" >{% csrf_token %}
        {% if form.errors %} {{ form.errors }} {% endif %}
        {% bootstrap_field form.name layout="horizontal" size="small" horizontal_field_class='col-md-8 mx-2' show_label=False set_placeholder=False show_help=False %}
        <button type="submit" class="btn btn-success">Done</button>
    </form>
    <a href="{% url 'mainpage:settings' %}" class="btn btn-secondary mt-5" role="button">Back</a>
</div>

{% endblock %}

templates/task_details.html
{% extends "base.html" %}

{% block title %}{{ task.name }}{% endblock %}

{% block content %}
  <h1>{{ task.name }}</h1>
  <p>
    Description {{ task.description }}
    Task for {{ task.assigned_to }} by {{ task.creator }}
  </p>
{% endblock %}

templates/tasks/edit_task.html
{% extends "base.html" %}

{% block title %}Edit task{% endblock %}

{% block content %}
<h1>Edit task</h1>
<form method="post" class="text-left" novalidate>{% csrf_token %}
    {% if form.errors %} {{ form.errors }} {% endif %}
    <div class="form-group">
        <label for="name">Task name</label>
        <input type="text" class="form-control" id="name" name="name" value="{{ form.name.value }}">
    </div>
    <div class="form-row mt-2">
        <div class="col-10">
            <label for="description">Description</label>
            <textarea class="form-control" id="description" rows="12" name="description">{{ form.description.value }}</textarea>
        </div>
        <div class="col-2">
            <label for="tags">Tags</label>
            <select multiple class="form-control" size="15" name="tags" >
                {% for tags in form.tags %}
                {{ tags }}
                {% endfor %}
            </select>
        </div>
    </div>
    <div class="form-row mt-2">
        <div class="col">
            <label for="status">Status</label>
            <select id="status" class="form-control" name="status">
                {% for status in form.status %}
                {{ status }}
                {% endfor %}
            </select>
            </div>
        <div class="col">
                <label for="creator">Creator</label>
                <select id="creator" class="form-control" name="creator">
                    {% for creator in form.creator %}
                    {{ creator }}
                    {% endfor %}
                </select>
        </div>
        <div class="col">
                <label for="assigned_to">Assigned to</label>
                <select id="assigned_to" class="form-control" name="assigned_to">
                    {% for assigned_to in form.assigned_to %}
                    {{ assigned_to }}
                    {% endfor %}
                </select>
        </div>
    </div>
    <div class="row justify-content-center my-3">
            <button class="btn btn-success mr-2" type='submit'>Save</button>
            <a href="{% url 'mainpage:home'%}" class="btn btn-secondary" role="button">Back</a>
    </div>
</form>
{% endblock %}

templates/tasks/home.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block title %} HOME {% endblock %} 
{% block content %}

<main role="main" class="inner cover">

    <!-- Filters -->
    <form method="GET" class="form-inline justify-content-center mt-3" action=".">
        
        {% if form.errors %} {{ form.errors }} {% endif %}
            <button name='newtask' action="{% url 'mainpage:new_task' %}" class="btn btn-success mr-2" type='submit'>Add new</button>
            <button name='mytasks' class="btn btn-primary mr-2" type='submit'>My tasks</button>
            <select id="assigned_to" class="form-control col-2 mr-2" name="assigned_to">
                <option class="text-align-center" selected>Assigned to</option>
                {% for user in users %}
                <option value="{{ user }}">{{ user }}</option>
                {% endfor %}
            </select>
            <select id="status" class="form-control col-2 mr-2" name="status">
                <option selected>Status</option>
                {% for status in statuses %}
                <option value="{{ status }}">{{ status }}</option>
                {% endfor %}
            </select>
            <select id="tag" class="form-control col-2 mr-2" name="tag">
                <option selected>Tag</option>
                {% for tag in tags %}
                <option value="{{ tag }}">{{ tag }}</option>
                {% endfor %}
            </select>
            <button class="btn btn-info mr-2" type="submit" >Apply</button>
            <button name='reset' class="btn btn-warning mr-2" type='submit'>Reset</button>
            
            
            
    </form>

    <!-- Buttons "My tasks" and "Add new" -->
    <div class="row justify-content-center my-3">
       
    </div>

    <!-- Head of task container -->
    <div class="row my-2 border-bottom border-secondary text-left">
        <div class="col-1 ">Tags</div>
        <div class="col-3 ">Name</div>
        <div class="col-5 ">Description</div>
        <div class="col-1 ">Status</div>
        <div class="col-1 ">Creator</div>
        <div class="col-1">Assigned</div>
    </div>

    <!-- Tasks -->
        {% for task in queryset %}
            <div class="row row-hover mb-2 text-left position-relative">
                    <div class="col-1 ">{{ task.tags.all|join:", "|truncatewords:3 }}</div>
                    <div class="col-3 position-static"><a class="stretched-link text-decoration-none" href="{{ task.get_absolute_url }}">
                        {{ task.name|truncatewords:10  }}</a></div>
                    <div class="col-5 ">{{ task.description|truncatewords:15|linebreaks }}</div>
                    <div class="col-1 text-truncate">{{ task.status }}</div>
                    <div class="col-1 text-truncate ">{{ task.creator }}</div>
                    <div class="col-1  text-truncate">{{ task.assigned_to }}</div>
            </div>
        {% endfor %}

</main>
{% endblock %}

templates/tasks/new_task.html
{% extends "base.html" %}

{% block title %}New task{% endblock %}

{% block content %}
<h1>New task</h1>
<form method="post" class="text-left" novalidate>{% csrf_token %}
    {% if form.errors %} {{ form.errors }} {% endif %}
    <div class="form-group">
        <label for="name">Task name</label>
        <input type="text" class="form-control" id="name" name="name" value="{{ form.name.value }}">
    </div>
    <div class="form-row mt-2">
        <div class="col-10">
            <label for="description">Description</label>
            <textarea class="form-control" id="description" rows="12" name="description">{{ form.description.value }}</textarea>
        </div>
        <div class="col-2">
            <label for="tags">Tags</label>
            <select multiple class="form-control" size="15" name="tags" >
                {% for tags in form.tags %}
                {{ tags }}
                {% endfor %}
            </select>
        </div>
    </div>
    <div class="form-row mt-2">
        <div class="col">
            <label for="status">Status</label>
            <select id="status" class="form-control" name="status">
                {% for status in form.status %}
                {{ status }}
                {% endfor %}
            </select>
            </div>
        <div class="col">
                <label for="creator">Creator</label>
                <select id="creator" class="form-control" name="creator">
                    {% for creator in form.creator %}
                    {{ creator }}
                    {% endfor %}
                </select>
        </div>
        <div class="col">
                <label for="assigned_to">Assigned to</label>
                <select id="assigned_to" class="form-control" name="assigned_to">
                    {% for assigned_to in form.assigned_to %}
                    {{ assigned_to }}
                    {% endfor %}
                </select>
        </div>
    </div>
    <!-- Buttons -->
    <div class="row justify-content-center my-3">
        <button  class="btn btn-success mr-2" type='submit'>Save</button>
        <a href="{% url 'mainpage:home'%}" class="btn btn-secondary" role="button">Back</a>
    </div>
</form>



{% endblock %}

templates/tasks/task_confirm_delete.html
{% extends "base.html" %}

{% block title %}Delete{% endblock %}

{% block content %}
<form method="post">{% csrf_token %}
    <h4>Do you really want to delete "{{ object }}"? </h4>
    <br><br>
    <p><input type="submit" class="btn btn-success" value="Yes"/>
    <a href="{% url 'mainpage:home' %}" class="btn btn-danger" role="button">No</a>

</form>
{% endblock %}

templates/tasks/view_task.html
{% extends "base.html" %}

{% block title %}{{ task.name }}{% endblock %}

{% block content %}
  <h1>View task</h1>
  <form method="post" class="text-left" novalidate>{% csrf_token %}
    <fieldset disabled>
      <div class="form-group">
          <label for="name">Task name</label>
          <input type="text" class="form-control" id="name" name="name" value="{{ task.name }}">
      </div>
      <div class="form-row mt-2">
          <div class="col-10">
              <label for="description">Description</label>
              <textarea class="form-control" id="description" rows="12" name="description">{{ task.description }}</textarea>
          </div>
          <div class="col-2">
              <label for="tags">Tags</label>
              <select multiple class="form-control text-left" size="15" name="tags" >
                  {% for tag in task.tags.all %}
                  <option>{{ tag }}</option>
                  {% endfor %}
              </select>
          </div>
      </div>
      <div class="form-row mt-2">
          <div class="col">
              <label for="status">Status</label>
              <input type="text" class="form-control" value="{{ task.status }}">
              </div>
        <div class="col">
                <label for="creator">Creator</label>
                <input type="text" class="form-control" value="{{ task.creator }}">
        </div>
        <div class="col">
                <label for="assigned_to">Assigned to</label>
                <input type="text" class="form-control" value="{{ task.assigned_to }}">

        </div>
      </div></fieldset></form>
      <div class="row justify-content-center my-3">
            
            <form method="GET" action="{% url 'mainpage:edit_task' task.id %}">{% csrf_token %}
                <button action="{% url 'mainpage:edit_task' task.pk %}" class="btn btn-success mr-2" type='submit'>Edit task</button>
            </form>
            <form method="GET" action="{% url 'mainpage:delete_task' task.pk%}">{% csrf_token %}
                <button class="btn btn-danger mr-1" type='submit'>Delete</button>
            <a href="{% url 'mainpage:home'%}" class="btn btn btn-secondary" role="button">Back</a>
    </div>
  
{% endblock %}